# .travis.yml 文件

# 聲明構建語言環境
language: android
# 配置信息
android:
  components:
    # 你可能需要修改下面兩項的版本
    - build-tools-28.0.3
    - android-28
    # Android Support Repository
    - extra-android-m2repository
    # Support Library
    - extra-android-support
script:

before_install:
  - chmod +x gradlew

before_deploy:
  # - ls app/build/outputs/apk/release/
  - ls app/build/outputs/apk/debug/

# 為構建添加暫存
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# 為構建添加暫存
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
